#!/bin/sh

cd ${PROMETHEUS_K8S_DATADIR}

exec /bin/config-controller \
  --configroot=${PROMETHEUS_K8S_CONFIGROOT} \
  --configmap=${PROMETHEUS_K8S_CONFIGMAP} \
  -- \
  /bin/prometheus \
  -config.file=${PROMETHEUS_K8S_CONFIGROOT}/prometheus.yml \
  -storage.local.path=${PROMETHEUS_K8S_DATADIR} \
  -web.console.libraries=/etc/prometheus/console_libraries \
  -web.console.templates=/etc/prometheus/consoles \
  ${PROMETHEUS_K8S_ARGS}
